apiVersion: v1
kind: Service
metadata:
  name: profile
  namespace: is402-profile
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "false"
spec:
  type: LoadBalancer
  selector:
    app: profile
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
